### PR TITLE
SEIRS with Leaky Vaccine

### PR DESCRIPTION
**Pull request by connor-vanmeter**
Resolves Issue #4 along with completed SEIR All-or-Nothing model

### CODE REVIEW

**Comment by smjenness** [comment]
Hi @connor-vanmeter: is this ready for me to review?

**Comment by connor-vanmeter** [comment]
Hey @smjenness.
I have two clarifying questions for the model before you take a look. May need to make some changes accordingly:

1. Is there a reduced force of infection for someone who has experienced the disease (ie. progressed from S->E->I->R->S)? I think we discussed not including this and the model as-is does not include any reduced force of infection for these individuals. I can include it but would have some follow-up questions on the degree of disease protection a vaccine protected individual who is also disease experienced and once again susceptible would have.

2. One of the assumptions I made was that a person who was vaccinated and was conferred protection would always have reduced force of infection due to the vaccine protection _even if they progressed through the model and once again became susceptible_. I was not sure if these individuals should be _considered_ unvaccinated if they progressed through the model and once again became susceptible even if they were vaccine protected before becoming infected. In short, I am wondering if these vaccine protected individuals should retain their vaccine protection even after disease progression and becoming susceptible. One possible issue with how I currently handle the situation is that it seems to conflict with the way that only susceptible individuals are eligible to become vaccine protected although all individuals, regardless of `status`, are eligible to become vaccinated.

If changes need to be made based on the questions above, then I can take those up Thursday.
Thanks!

**Comment by venkataduvvuri** [comment]
The reduction in the force of infection after immunization depends on the vaccine effectiveness, pathogen evolution and the longevity of the vaccine-induced immunity.  For instance, influenza viruses evolve faster so there is a need for upgrading the annual influenza vaccine with the circulating viruses. In this case, there will be two scenarios:

**1. Vaccine effectiveness**: A person who took an influenza vaccine in the previous year may not necessarily be protected and need to have an updated vaccine to be protected from the newly emerged and circulating strains.

2.  Longevity of immunity: This depends on the type of influenza vaccine - a) Trivalent Inactivated Influenza Vaccine (seasonal flu vaccine) and b) Live attenuated influenza vaccine (LAIV). 

a) TIV may provide protection for about ~6months 
[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4362519/]

b) LAIV may protect for about one year
 
_**References:**_
Mohn KG, Bredholt G, Brokstad KA, Pathirana RD, Aarstad HJ, Tøndel C, Cox RJ. Longevity of B-cell and T-cell responses after live attenuated influenza vaccination in children. J Infect Dis. 2015 May 15;211(10):1541-9. [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4407761/] 

Ambrose CS, Yi T, Walker RE, Connor EM. Duration of protection provided by live attenuated influenza vaccine in children. Pediatr Infect Dis J. 2008 Aug;27(8):744-8.

This would suggest that though a person had an influenza vaccine in a season, will lose the protection as time move forward and become susceptible for the emergent strain.

However, this may be entirely different with other viruses. Hope this helps and let me know if more information on this.

**Comment by connor-vanmeter** [comment]
Thanks @venkataduvvuri for the notes and for the helpful suggestions and considerations!

**Pull request merged**
